
BLOCKCHAIN_DUST = 0.0000275
TX_FEES = 0.0001
TOTAL_FEE = BLOCKCHAIN_DUST + TX_FEES
REMOTE_CONNECT = True
BATCH_SIZE = 10
COIN = 100000000

DATA_FOLDER = "data/"
UNSIGNED_CERTS_FOLDER = DATA_FOLDER + "unsigned_certs/"
SIGNED_CERTS_FOLDER = DATA_FOLDER + "signed_certs/"
HASHED_CERTS_FOLDER = DATA_FOLDER + "hashed_certs/"
UNSIGNED_TXS_FOLDER = DATA_FOLDER + "unsigned_txs/"
UNSENT_TXS_FOLDER = DATA_FOLDER + "unsent_txs/"
SENT_TXS_FOLDER = DATA_FOLDER + "sent_txs/"
# UNSENT_CERTS_FOLDER = DATA_FOLDER + "unsent_certs/"
# SENT_CERTS_FOLDER = DATA_FOLDER + "sent_certs/"