
BLOCKCHAIN_DUST = 0.0000275
TX_FEES = 0.0001
TOTAL_FEE = BLOCKCHAIN_DUST + TX_FEES

DATA_FOLDER = "data/"
UNSIGNED_CERTS_FOLDER = DATA_FOLDER + "unsigned_certs/"
SIGNED_CERTS_FOLDER = DATA_FOLDER + "signed_certs/"
HASHED_CERTS_FOLDER = DATA_FOLDER + "hashed_certs/"
UNSENT_CERTS_FOLDER = DATA_FOLDER + "unsent_certs/"
SENT_CERTS_FOLDER = DATA_FOLDER + "sent_certs/"